package com.aaliyun.leadnews.article.service;
import com.aaliyun.leadnews.model.search.ArticleSearchDocument;
import com.alibaba.csp.sentinel.annotation.SentinelResource;
import com.alibaba.csp.sentinel.slots.block.BlockException;
import com.aaliyun.leadnews.common.sentinel.SentinelResources;
import io.micrometer.core.instrument.MeterRegistry;
import com.aaliyun.leadnews.article.domain.*;import com.aaliyun.leadnews.article.mapper.*;import com.aaliyun.leadnews.common.api.CommonErrorCode;import com.aaliyun.leadnews.common.context.UserContext;import com.aaliyun.leadnews.common.exception.BusinessException;import com.aaliyun.leadnews.feign.behavior.BehaviorInternalClient;import com.aaliyun.leadnews.model.behavior.ArticleBehaviorView;import com.aaliyun.leadnews.model.foundation.*;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class ArticleApplicationService {
 private final ArticleMapper articles;private final ArticleContentMapper contents;private final ChannelMapper channels;private final ObjectMapper json;private final BehaviorInternalClient behavior;private final MeterRegistry metrics;
 public ArticleApplicationService(ArticleMapper a,ArticleContentMapper c,ChannelMapper ch,ObjectMapper j,BehaviorInternalClient b,MeterRegistry m){articles=a;contents=c;channels=ch;json=j;behavior=b;metrics=m;}
 @Transactional public ArticleCreatedResponse create(CreateArticleCommand c){requireAdminInternal();Article existing=byWm(c.wmNewsId());if(existing!=null)return new ArticleCreatedResponse(existing.getId(),false);Channel channel=channels.selectById(c.channelId());if(channel==null||!"ENABLED".equals(channel.getStatus()))throw new BusinessException(40000,"Channel is unavailable");Article a=new Article();a.setWmNewsId(c.wmNewsId());a.setAuthorId(c.authorId());a.setAuthorName(c.authorName());a.setChannelId(c.channelId());a.setChannelName(channel.getName());a.setTitle(c.title());a.setLayout(c.layout());a.setCoverImages(write(c.coverImages()==null?List.of():c.coverImages()));a.setLabels(c.labels());a.setPublishTime(c.publishTime()==null?LocalDateTime.now():c.publishTime());a.setStatus("APPROVED");a.setPublishStatus(a.getPublishTime().isAfter(LocalDateTime.now())?"WAITING":"APPROVED");a.setPublishRetryCount(0);try{articles.insert(a);ArticleContent content=new ArticleContent();content.setArticleId(a.getId());content.setContent(write(c.content()));contents.insert(content);return new ArticleCreatedResponse(a.getId(),true);}catch(DuplicateKeyException e){Article raced=byWm(c.wmNewsId());if(raced!=null)return new ArticleCreatedResponse(raced.getId(),false);throw e;}}
 @SentinelResource(value=SentinelResources.ARTICLE_DETAIL,blockHandler="detailBlocked") public ArticleView detail(Long id){Article a=articles.selectById(id);if(a==null||!"PUBLISHED".equals(a.getStatus()))throw new BusinessException(40400,"Article not found");ArticleContent c=contents.selectOne(new LambdaQueryWrapper<ArticleContent>().eq(ArticleContent::getArticleId,id));return view(a,c);}
 public ArticleView detailBlocked(Long id,BlockException ex){metrics.counter(SentinelResources.METRIC_NAME,"resource",SentinelResources.ARTICLE_DETAIL).increment();throw new BusinessException(CommonErrorCode.HOT_PARAM_RATE_LIMITED);}
 public PageResponse<ArticleView> list(Long channelId,LocalDateTime before,long page,long size){Page<Article> p=new Page<>(page,Math.min(size,100));LambdaQueryWrapper<Article> q=new LambdaQueryWrapper<Article>().eq(Article::getStatus,"PUBLISHED").eq(Article::getDeleted,false).eq(channelId!=null,Article::getChannelId,channelId).le(before!=null,Article::getPublishTime,before).orderByDesc(Article::getPublishTime);articles.selectPage(p,q);return new PageResponse<>(p.getTotal(),page,size,p.getRecords().stream().map(a->view(a,contents.selectOne(new LambdaQueryWrapper<ArticleContent>().eq(ArticleContent::getArticleId,a.getId())))).toList());}
 public List<ChannelDTO> enabledChannels(){return channels.selectList(new LambdaQueryWrapper<Channel>().eq(Channel::getStatus,"ENABLED").eq(Channel::getDeleted,false).orderByAsc(Channel::getOrd)).stream().map(this::dto).toList();}
 public ArticleSearchDocument searchDocument(Long id){requireInternal();Article a=articles.selectById(id);if(a==null||!"PUBLISHED".equals(a.getStatus())||Boolean.TRUE.equals(a.getDeleted()))throw new BusinessException(40400,"Published article not found");return searchDocument(a);}
 public PageResponse<ArticleSearchDocument> searchDocuments(long page,long size){requireInternal();Page<Article> p=new Page<>(Math.max(1,page),Math.min(200,Math.max(1,size)));articles.selectPage(p,new LambdaQueryWrapper<Article>().eq(Article::getStatus,"PUBLISHED").eq(Article::getDeleted,false).orderByAsc(Article::getId));return new PageResponse<>(p.getTotal(),p.getCurrent(),p.getSize(),p.getRecords().stream().map(this::searchDocument).toList());}
 private ArticleSearchDocument searchDocument(Article a){ArticleContent c=contents.selectOne(new LambdaQueryWrapper<ArticleContent>().eq(ArticleContent::getArticleId,a.getId()));List<ArticleContentItemDTO> items=read(c.getContent(),new TypeReference<List<ArticleContentItemDTO>>(){});String text=items.stream().filter(i->"text".equalsIgnoreCase(i.type())).map(ArticleContentItemDTO::value).filter(Objects::nonNull).reduce("",(x,y)->x.isEmpty()?y:x+"\n"+y);List<String> labelList=a.getLabels()==null?List.of():Arrays.stream(a.getLabels().split("[,，\\s]+")).map(String::trim).filter(s->!s.isEmpty()).distinct().toList();return new ArticleSearchDocument(a.getId(),a.getTitle(),text,a.getSummary(),a.getAuthorId(),a.getAuthorName(),a.getChannelId(),a.getChannelName(),labelList,a.getPublishedTime()==null?a.getPublishTime():a.getPublishedTime(),a.getStaticUrl(),a.getCreatedTime());}
 private Article byWm(Long id){return articles.selectOne(new LambdaQueryWrapper<Article>().eq(Article::getWmNewsId,id).eq(Article::getDeleted,false));}private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new BusinessException(CommonErrorCode.VALIDATION);}}private <T>T read(String s,TypeReference<T> t){try{return json.readValue(s,t);}catch(Exception e){throw new BusinessException(50000,"Stored JSON is invalid");}}
 public String staticObjectKey(Long id){Article a=articles.selectById(id);if(a==null||!"PUBLISHED".equals(a.getPublishStatus())||a.getStaticObjectKey()==null)throw new BusinessException(40400,"Published static article not found");return a.getStaticObjectKey();}
 private ArticleView view(Article a,ArticleContent c){ArticleBehaviorView b=behavior(a.getId());return new ArticleView(a.getId(),a.getWmNewsId(),a.getTitle(),a.getAuthorId(),a.getAuthorName(),a.getChannelId(),a.getChannelName(),read(c.getContent(),new TypeReference<List<ArticleContentItemDTO>>(){}),read(a.getCoverImages(),new TypeReference<List<String>>(){}),a.getLabels(),a.getPublishTime(),a.getSummary(),a.getSummaryStatus(),"SUCCESS".equals(a.getSummaryStatus()),a.getSummaryGeneratedTime(),a.getStaticUrl(),a.getStaticObjectKey(),a.getPublishStatus(),a.getPublishedTime(),b.likeCount(),b.viewCount(),b.commentCount(),b.collectCount(),b.liked(),b.realtime());}
 private ArticleBehaviorView behavior(Long id){try{ArticleBehaviorView r=behavior.articleBehavior(id);return r==null?emptyBehavior():r;}catch(RuntimeException e){return emptyBehavior();}}private ArticleBehaviorView emptyBehavior(){return new ArticleBehaviorView(0,0,0,0,false,false);}
 private ChannelDTO dto(Channel c){return new ChannelDTO(c.getId(),c.getName(),c.getDescription(),c.getStatus(),c.getOrd(),c.getCreatedTime(),c.getUpdatedTime());}private void requireAdminInternal(){if(!UserContext.isInternal())throw new BusinessException(CommonErrorCode.AUTH_FORBIDDEN);}private void requireInternal(){if(!UserContext.isInternal())throw new BusinessException(CommonErrorCode.AUTH_FORBIDDEN);}
 public record ArticleView(Long id,Long wmNewsId,String title,Long authorId,String authorName,Long channelId,String channelName,List<ArticleContentItemDTO> content,List<String> coverImages,String labels,LocalDateTime publishTime,String summary,String summaryStatus,boolean summaryGenerated,LocalDateTime summaryGeneratedTime,String staticUrl,String staticObjectKey,String publishStatus,LocalDateTime publishedTime,long likeCount,long viewCount,long commentCount,long collectCount,boolean liked,boolean behaviorRealtime){}
}
