package com.aaliyun.leadnews.article.service;
import com.aaliyun.leadnews.article.config.SearchSyncProperties;import com.aaliyun.leadnews.article.domain.ArticleSearchSync;import com.aaliyun.leadnews.article.mapper.ArticleSearchSyncMapper;import com.aaliyun.leadnews.common.trace.TraceContext;import com.aaliyun.leadnews.model.search.ArticleSearchEvent;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import org.slf4j.*;import org.springframework.kafka.core.KafkaTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import java.util.concurrent.TimeUnit;
@Service public class ArticleSearchOutboxService {
 private static final Logger log=LoggerFactory.getLogger(ArticleSearchOutboxService.class);private final ArticleSearchSyncMapper mapper;private final KafkaTemplate<String,ArticleSearchEvent> kafka;private final SearchSyncProperties p;
 public ArticleSearchOutboxService(ArticleSearchSyncMapper m,KafkaTemplate<String,ArticleSearchEvent> k,SearchSyncProperties p){mapper=m;kafka=k;this.p=p;}
 @Transactional public void enqueue(Long articleId,long articleVersion,ArticleSearchEvent.EventType type){ArticleSearchSync x=new ArticleSearchSync();x.setEventId(UUID.randomUUID().toString());x.setArticleId(articleId);x.setArticleVersion(articleVersion);x.setEventType(type.name());x.setTraceId(TraceContext.getTraceId());x.setStatus("PENDING");x.setRetryCount(0);x.setNextRetryTime(LocalDateTime.now());mapper.insert(x);}
 @Scheduled(fixedDelayString="${leadnews.search-sync.retry-delay-ms:5000}") public void dispatch(){LocalDateTime now=LocalDateTime.now();mapper.recoverExpired(now.minus(p.claimTimeout()),now);List<ArticleSearchSync> rows=mapper.selectList(new LambdaQueryWrapper<ArticleSearchSync>().eq(ArticleSearchSync::getStatus,"PENDING").le(ArticleSearchSync::getNextRetryTime,now).orderByAsc(ArticleSearchSync::getId).last("LIMIT "+p.batchSize()));for(ArticleSearchSync row:rows)if(mapper.claim(row.getId(),LocalDateTime.now())==1)send(row);}
 private void send(ArticleSearchSync row){try{ArticleSearchEvent event=new ArticleSearchEvent(row.getEventId(),row.getArticleId(),row.getArticleVersion(),ArticleSearchEvent.EventType.valueOf(row.getEventType()),row.getCreatedTime().atZone(ZoneId.systemDefault()).toInstant(),row.getTraceId());kafka.send(p.topic(),row.getArticleId().toString(),event).get(10,TimeUnit.SECONDS);if(mapper.markSent(row.getId())!=1)log.warn("Search outbox sent but lease was lost, eventId={}; at-least-once redelivery is safe",row.getEventId());}catch(Exception e){int retry=row.getRetryCount()+1;String status=retry>=p.maxRetries()?"DEAD":"PENDING";LocalDateTime next=LocalDateTime.now().plusSeconds(Math.min(300,1L<<Math.min(retry,8)));mapper.markFailure(row.getId(),status,retry,next,safe(e));log.warn("Search outbox send failed eventId={} status={} retry={}",row.getEventId(),status,retry);}}
 private String safe(Exception e){String m=e.getMessage();if(m==null)m=e.getClass().getSimpleName();return m.substring(0,Math.min(500,m.length()));}
}
