package com.aaliyun.leadnews.article.service;
import com.aaliyun.leadnews.article.domain.Article;import com.aaliyun.leadnews.article.mapper.ArticleMapper;import com.aaliyun.leadnews.common.redis.BehaviorRedisKeys;import com.aaliyun.leadnews.model.foundation.PageResponse;import com.aaliyun.leadnews.model.hot.*;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.baomidou.mybatisplus.extension.plugins.pagination.Page;import org.springframework.data.redis.core.StringRedisTemplate;import org.springframework.data.redis.core.ZSetOperations;import org.springframework.stereotype.Service;import java.time.LocalDateTime;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;
@Service public class HotArticleQueryService {private final ArticleMapper mapper;private final StringRedisTemplate redis;public HotArticleQueryService(ArticleMapper m,StringRedisTemplate r){mapper=m;redis=r;}
 public HotArticleResponse hot(Long channelId,int requested){int limit=Math.min(50,Math.max(1,requested));String key=channelId==null?BehaviorRedisKeys.HOT_GLOBAL:BehaviorRedisKeys.hotChannel(channelId);try{Set<ZSetOperations.TypedTuple<String>> tuples=redis.opsForZSet().reverseRangeWithScores(key,0,limit-1);if(tuples==null||tuples.isEmpty())return fallback(channelId,limit);List<Long> ids=tuples.stream().map(t->Long.valueOf(t.getValue())).toList();Map<Long,HotArticleSummary> found=batch(new ArticleBatchRequest(ids)).stream().collect(Collectors.toMap(HotArticleSummary::articleId,Function.identity()));List<HotArticleItem> result=new ArrayList<>();for(var t:tuples){Long id=Long.valueOf(t.getValue());HotArticleSummary a=found.get(id);if(a==null){redis.opsForZSet().remove(key,t.getValue());redis.opsForZSet().remove(BehaviorRedisKeys.HOT_GLOBAL,t.getValue());}else result.add(new HotArticleItem(a,t.getScore()==null?0:t.getScore()));}return new HotArticleResponse(false,result);}catch(Exception e){return fallback(channelId,limit);}}
 private HotArticleResponse fallback(Long channelId,int limit){var q=new LambdaQueryWrapper<Article>().eq(Article::getStatus,"PUBLISHED").eq(channelId!=null,Article::getChannelId,channelId).orderByDesc(Article::getPublishedTime).last("LIMIT "+limit);return new HotArticleResponse(true,mapper.selectList(q).stream().map(a->new HotArticleItem(summary(a),0)).toList());}
 public List<HotArticleSummary> batch(ArticleBatchRequest request){if(request.articleIds().isEmpty())return List.of();return mapper.selectBatchIds(request.articleIds()).stream().filter(a->"PUBLISHED".equals(a.getStatus())).map(this::summary).toList();}
 public PageResponse<HotArticleMetadata> metadata(long page,long size,LocalDateTime after){Page<Article> p=mapper.selectPage(Page.of(page,Math.min(200,size)),new LambdaQueryWrapper<Article>().eq(Article::getStatus,"PUBLISHED").ge(Article::getPublishedTime,after).orderByAsc(Article::getId));return new PageResponse<>(p.getTotal(),p.getCurrent(),p.getSize(),p.getRecords().stream().map(a->new HotArticleMetadata(a.getId(),a.getChannelId(),published(a))).toList());}
 public void cleanup(long id){Article a=mapper.selectById(id);if(a!=null)new ArticleHotMetadataService(redis).remove(id,a.getChannelId());}
 private HotArticleSummary summary(Article a){return new HotArticleSummary(a.getId(),a.getChannelId(),a.getTitle(),a.getSummary(),a.getStaticUrl(),published(a));}private LocalDateTime published(Article a){return a.getPublishedTime()!=null?a.getPublishedTime():a.getPublishTime();}
}
