package com.aaliyun.leadnews.article.service;
import com.aaliyun.leadnews.article.config.AiSummaryProperties;import com.aaliyun.leadnews.article.domain.*;import com.aaliyun.leadnews.article.mapper.*;import com.aaliyun.leadnews.common.context.UserContext;import com.aaliyun.leadnews.common.exception.BusinessException;import com.aaliyun.leadnews.feign.ai.AiInternalClient;import com.aaliyun.leadnews.model.ai.*;import com.baomidou.mybatisplus.core.MybatisConfiguration;import com.baomidou.mybatisplus.core.metadata.TableInfoHelper;import com.fasterxml.jackson.databind.ObjectMapper;import io.micrometer.core.instrument.simple.SimpleMeterRegistry;import org.apache.ibatis.builder.MapperBuilderAssistant;import org.junit.jupiter.api.AfterEach;import org.junit.jupiter.api.Test;import org.springframework.kafka.core.KafkaTemplate;import org.springframework.test.util.ReflectionTestUtils;import java.time.*;import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class ArticleAiSummaryServiceTest{
 static{var a=new MapperBuilderAssistant(new MybatisConfiguration(),"test");TableInfoHelper.initTableInfo(a,ArticleAiSummaryTask.class);TableInfoHelper.initTableInfo(a,Article.class);}
 ArticleMapper articles=mock(ArticleMapper.class);ArticleContentMapper contents=mock(ArticleContentMapper.class);ArticleAiSummaryTaskMapper tasks=mock(ArticleAiSummaryTaskMapper.class);AiInternalClient ai=mock(AiInternalClient.class);KafkaTemplate<String,Object> kafka=mock(KafkaTemplate.class);AiSummaryProperties p=new AiSummaryProperties(true,10,100,3,Duration.ofMinutes(2),5000,20);ArticleAiSummaryService service=new ArticleAiSummaryService(articles,contents,tasks,ai,kafka,new ObjectMapper(),p,new SimpleMeterRegistry());
 private Article article(long version){Article a=new Article();ReflectionTestUtils.setField(a,"id",1L);a.setPublishStatus("PUBLISHED");a.setStatus("PUBLISHED");a.setSummaryVersion(version);a.setTitle("title");a.setLabels("tech");a.setPublishedTime(LocalDateTime.now());return a;}private ArticleAiSummaryTask task(long version){ArticleAiSummaryTask t=new ArticleAiSummaryTask();ReflectionTestUtils.setField(t,"id",2L);t.setArticleId(1L);t.setSummaryVersion(version);t.setEventId("event");t.setStatus("SENT");t.setRetryCount(0);return t;}
 @AfterEach void clearContext(){UserContext.clear();}
 @Test void duplicateEventDoesNotCallAi(){when(tasks.selectOne(any())).thenReturn(task(1));when(tasks.update(isNull(),any())).thenReturn(0);service.consume(new ArticlePublishedEvent("event",1L,1,Instant.now(),Instant.now(),"t"));verifyNoInteractions(ai);}
 @Test void oldVersionIsMarkedStale(){when(tasks.selectOne(any())).thenReturn(task(1));when(tasks.update(isNull(),any())).thenReturn(1);when(articles.selectById(1L)).thenReturn(article(2));service.consume(new ArticlePublishedEvent("event",1L,1,Instant.now(),Instant.now(),"t"));verifyNoInteractions(ai);verify(tasks,atLeast(2)).update(isNull(),any());}
 @Test void aiFailureNeverChangesPublishedFact(){Article a=article(1);ArticleContent c=new ArticleContent();c.setContent("[{\"type\":\"text\",\"value\":\"正文内容\"}]");when(tasks.selectOne(any())).thenReturn(task(1));when(tasks.update(isNull(),any())).thenReturn(1);when(articles.update(isNull(),any())).thenReturn(1);when(articles.selectById(1L)).thenReturn(a);when(contents.selectOne(any())).thenReturn(c);when(ai.summarize(any())).thenThrow(new RuntimeException("provider down"));service.consume(new ArticlePublishedEvent("event",1L,1,Instant.now(),Instant.now(),"t"));assertThat(a.getPublishStatus()).isEqualTo("PUBLISHED");verify(articles,atLeastOnce()).update(isNull(),any());}
 @Test void failedSummaryIsPreciselyReopened(){internal();Article a=article(4);a.setSummaryStatus("FAILED");ArticleAiSummaryTask t=task(4);t.setStatus("FAILED");t.setRetryCount(3);when(articles.selectById(13L)).thenReturn(a);when(tasks.selectOne(any())).thenReturn(t);when(articles.update(isNull(),any())).thenReturn(1);when(tasks.update(isNull(),any())).thenReturn(1);var result=service.retryFailed(13L);assertThat(result.articleId()).isEqualTo(13L);assertThat(result.summaryVersion()).isEqualTo(4);assertThat(result.summaryStatus()).isEqualTo("PENDING");assertThat(result.reopened()).isTrue();verify(tasks).selectOne(any());verify(tasks).update(isNull(),any());verifyNoInteractions(ai);}
 @Test void successfulSummaryRetryIsIdempotent(){internal();Article a=article(4);a.setSummaryStatus("SUCCESS");when(articles.selectById(13L)).thenReturn(a);assertThat(service.retryFailed(13L).reopened()).isFalse();verifyNoInteractions(tasks,ai);}
 @Test void nonPublishedSummaryRetryIsRejected(){internal();Article a=article(4);a.setPublishStatus("APPROVED");a.setSummaryStatus("FAILED");when(articles.selectById(13L)).thenReturn(a);assertThatThrownBy(()->service.retryFailed(13L)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo(40900);}
 @Test void missingArticleRetryIsNotFound(){internal();when(articles.selectById(404L)).thenReturn(null);assertThatThrownBy(()->service.retryFailed(404L)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo(40400);}
 @Test void duplicateConcurrentRetryHasOnlyOneTransition(){internal();Article failed=article(4);failed.setSummaryStatus("FAILED");Article pending=article(4);pending.setSummaryStatus("PENDING");ArticleAiSummaryTask t=task(4);t.setStatus("FAILED");when(articles.selectById(13L)).thenReturn(failed,pending);when(tasks.selectOne(any())).thenReturn(t);when(articles.update(isNull(),any())).thenReturn(1);when(tasks.update(isNull(),any())).thenReturn(1);assertThat(service.retryFailed(13L).reopened()).isTrue();assertThat(service.retryFailed(13L).reopened()).isFalse();verify(tasks,times(1)).update(isNull(),any());verifyNoInteractions(ai);}
 @Test void preciseRetryRequiresTrustedInternalMarker(){Article a=article(4);a.setSummaryStatus("FAILED");when(articles.selectById(13L)).thenReturn(a);assertThatThrownBy(()->service.retryFailed(13L)).isInstanceOf(BusinessException.class).extracting("code").isEqualTo(40300);verifyNoInteractions(articles,tasks,ai);}
 private void internal(){UserContext.setInternal(true);}
}
