CREATE TABLE IF NOT EXISTS ap_channel (
  id BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(64) NOT NULL, description VARCHAR(255) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED', ord INT NOT NULL DEFAULT 0,
  created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0, deleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY(id), UNIQUE KEY uk_ap_channel_name(name), KEY idx_channel_status_ord(status,ord)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS ap_article (
  id BIGINT NOT NULL AUTO_INCREMENT, wm_news_id BIGINT NOT NULL, author_id BIGINT NOT NULL, author_name VARCHAR(64) NOT NULL,
  channel_id BIGINT NOT NULL, channel_name VARCHAR(64) NOT NULL, title VARCHAR(128) NOT NULL, layout TINYINT NOT NULL DEFAULT 0,
  cover_images JSON NULL, labels VARCHAR(255) NULL, publish_time DATETIME(3) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
  summary VARCHAR(500) NULL, static_url VARCHAR(500) NULL,
  created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  version INT NOT NULL DEFAULT 0, deleted TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY(id), UNIQUE KEY uk_ap_article_wm_news(wm_news_id), KEY idx_article_channel_publish(channel_id,publish_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE IF NOT EXISTS ap_article_content (
  id BIGINT NOT NULL AUTO_INCREMENT, article_id BIGINT NOT NULL, content JSON NOT NULL,
  created_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY(id), UNIQUE KEY uk_article_content_article(article_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO ap_channel(name,description,status,ord) VALUES ('推荐','本地开发默认频道','ENABLED',1),('科技','科技资讯','ENABLED',2)
ON DUPLICATE KEY UPDATE description=VALUES(description);
