package com.aaliyun.leadnews.search.config;
import co.elastic.clients.elasticsearch.ElasticsearchClient;import org.springframework.stereotype.Component;import jakarta.annotation.PostConstruct;import java.io.*;
@Component public class SearchIndexInitializer{public static final String ARTICLE_INDEX="leadnews_article_v1",ARTICLE_ALIAS="leadnews_article",SUGGEST_INDEX="leadnews_suggestion_v1",SUGGEST_ALIAS="leadnews_suggestion";private final ElasticsearchClient client;public SearchIndexInitializer(ElasticsearchClient c){client=c;}@PostConstruct public void initialize()throws IOException{article();suggestion();}
 private void article()throws IOException{if(!client.indices().exists(e->e.index(ARTICLE_INDEX)).value()){String json="""
 {"settings":{"number_of_shards":1,"number_of_replicas":0},"mappings":{"dynamic":"strict","properties":{"articleId":{"type":"long"},"title":{"type":"text","analyzer":"standard"},"content":{"type":"text","analyzer":"standard"},"summary":{"type":"text","analyzer":"standard"},"authorId":{"type":"long"},"authorName":{"type":"keyword"},"channelId":{"type":"long"},"channelName":{"type":"keyword"},"labels":{"type":"keyword"},"publishTime":{"type":"date"},"staticUrl":{"type":"keyword","index":false},"createdTime":{"type":"date"}}},"aliases":{"leadnews_article":{}}}
 """;client.indices().create(c->c.index(ARTICLE_INDEX).withJson(new StringReader(json)));}}
 private void suggestion()throws IOException{if(!client.indices().exists(e->e.index(SUGGEST_INDEX)).value()){String json="""
 {"settings":{"number_of_shards":1,"number_of_replicas":0,"analysis":{"filter":{"leadnews_edge":{"type":"edge_ngram","min_gram":1,"max_gram":20}},"analyzer":{"leadnews_suggest":{"type":"custom","tokenizer":"standard","filter":["lowercase","leadnews_edge"]}}}},"mappings":{"dynamic":"strict","properties":{"articleId":{"type":"long"},"title":{"type":"keyword"},"suggestion":{"type":"text","analyzer":"leadnews_suggest","search_analyzer":"standard"},"labels":{"type":"keyword"}}},"aliases":{"leadnews_suggestion":{}}}
 """;client.indices().create(c->c.index(SUGGEST_INDEX).withJson(new StringReader(json)));}}}
