events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript application/xml;

    map $http_upgrade $connection_upgrade { default upgrade; '' close; }

    server {
        listen 80;
        root /srv/leadnews-app;
        include /etc/nginx/conf.d/leadnews-spa.inc;
    }
    server {
        listen 81;
        root /srv/leadnews-wemedia;
        include /etc/nginx/conf.d/leadnews-spa.inc;
    }
    server {
        listen 82;
        root /srv/leadnews-admin;
        include /etc/nginx/conf.d/leadnews-spa.inc;
    }
}
