package com.aaliyun.leadnews.admin.service;import com.aaliyun.leadnews.admin.domain.*;import com.aaliyun.leadnews.admin.mapper.*;import com.aaliyun.leadnews.common.api.CommonErrorCode;import com.aaliyun.leadnews.common.context.UserContext;import com.aaliyun.leadnews.common.exception.BusinessException;import com.aaliyun.leadnews.common.security.JwtTokenService;import com.aaliyun.leadnews.feign.article.ArticleInternalClient;import com.aaliyun.leadnews.feign.schedule.ScheduleInternalClient;import com.aaliyun.leadnews.feign.wemedia.WemediaAuditClient;import com.aaliyun.leadnews.model.foundation.*;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import org.springframework.dao.DuplicateKeyException;import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class AdminApplicationService {private final AdminUserMapper users;private final AuditRecordMapper audits;private final BCryptPasswordEncoder passwords;private final JwtTokenService jwt;private final WemediaAuditClient wemedia;private final ArticleInternalClient article;private final ScheduleInternalClient schedule;public AdminApplicationService(AdminUserMapper u,AuditRecordMapper a,BCryptPasswordEncoder p,JwtTokenService j,WemediaAuditClient w,ArticleInternalClient ar,ScheduleInternalClient s){users=u;audits=a;passwords=p;jwt=j;wemedia=w;article=ar;schedule=s;}
 public LoginResult login(String name,String password){AdminUser u=users.selectOne(new LambdaQueryWrapper<AdminUser>().eq(AdminUser::getName,name).eq(AdminUser::getDeleted,false));if(u==null||!"ACTIVE".equals(u.getStatus())||!passwords.matches(password,u.getPasswordHash()))throw new BusinessException(CommonErrorCode.AUTH_UNAUTHORIZED);long exp=7200;return new LoginResult(jwt.createToken(u.getId(),"ADMIN",Duration.ofSeconds(exp)),exp,u.getId(),u.getNickname());}
 public PageResponse<WmNewsSnapshot> pending(long page,long size){guard();return wemedia.pending(page,size);}public WmNewsSnapshot detail(Long id){guard();return wemedia.detail(id);}
 @Transactional public ApproveResult approve(Long id){guard();WmNewsSnapshot n=wemedia.approve(id);CreateArticleCommand c=new CreateArticleCommand(n.id(),n.userId(),n.authorName(),n.channelId(),n.title(),n.layout(),n.coverImages(),n.labels(),n.content(),n.publishTime());ArticleCreatedResponse result=article.create(c);record(id,"APPROVED",null);if(n.publishTime()!=null&&n.publishTime().isAfter(LocalDateTime.now())){Long taskId=schedule.create(new ScheduleTaskCommand(result.articleId(),n.publishTime()));return new ApproveResult(id,result.articleId(),result.created(),"WAITING",taskId);}PublishResponse published=article.publish(result.articleId());return new ApproveResult(id,result.articleId(),result.created(),published.status(),null);}
 @Transactional public WmNewsSnapshot reject(Long id,String reason){guard();if(reason==null||reason.isBlank())throw new BusinessException(CommonErrorCode.VALIDATION);WmNewsSnapshot n=wemedia.reject(id,reason);record(id,"REJECTED",reason);return n;}
 public List<ChannelDTO> channels(){guard();return article.channels();}public ChannelDTO createChannel(ChannelDTO c){guard();return article.createChannel(c);}public ChannelDTO updateChannel(Long id,ChannelDTO c){guard();return article.updateChannel(id,c);}public ChannelDTO channelStatus(Long id,String s){guard();return article.status(id,s);}public void deleteChannel(Long id){guard();article.deleteChannel(id);}
 private void record(Long news,String decision,String reason){AuditRecord existing=audits.selectOne(new LambdaQueryWrapper<AuditRecord>().eq(AuditRecord::getWmNewsId,news));if(existing!=null)return;AuditRecord r=new AuditRecord();r.setWmNewsId(news);r.setReviewerId(UserContext.getUserId());r.setDecision(decision);r.setReason(reason);r.setReviewedTime(LocalDateTime.now());try{audits.insert(r);}catch(DuplicateKeyException ignored){}}
 private void guard(){if(!UserContext.isType("ADMIN"))throw new BusinessException(CommonErrorCode.AUTH_FORBIDDEN);}public record LoginResult(String token,long expiresIn,Long userId,String nickname){}public record ApproveResult(Long wmNewsId,Long articleId,boolean articleCreated,String publishStatus,Long scheduleTaskId){}
}
