package com.aaliyun.leadnews.admin.web;import com.aaliyun.leadnews.admin.service.AdminApplicationService;import com.aaliyun.leadnews.common.api.ResponseResult;import com.aaliyun.leadnews.model.foundation.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/admin")public class AdminController{private final AdminApplicationService service;public AdminController(AdminApplicationService s){service=s;}
 @PostMapping("/login")public ResponseResult<AdminApplicationService.LoginResult>login(@Valid @RequestBody LoginRequest r){return ResponseResult.success(service.login(r.name(),r.password()));}
 @GetMapping("/audit/news")public ResponseResult<PageResponse<WmNewsSnapshot>>pending(@RequestParam(defaultValue="1")@Min(1)long page,@RequestParam(defaultValue="10")@Min(1)@Max(100)long size){return ResponseResult.success(service.pending(page,size));}
 @GetMapping("/audit/news/{id}")public ResponseResult<WmNewsSnapshot>detail(@PathVariable Long id){return ResponseResult.success(service.detail(id));}
 @PostMapping("/audit/news/{id}/approve")public ResponseResult<AdminApplicationService.ApproveResult>approve(@PathVariable Long id){return ResponseResult.success(service.approve(id));}
 @PostMapping("/audit/news/{id}/reject")public ResponseResult<WmNewsSnapshot>reject(@PathVariable Long id,@Valid @RequestBody RejectRequest r){return ResponseResult.success(service.reject(id,r.reason()));}
 @GetMapping("/channels")public ResponseResult<List<ChannelDTO>>channels(){return ResponseResult.success(service.channels());}@PostMapping("/channels")public ResponseResult<ChannelDTO>create(@Valid @RequestBody ChannelDTO c){return ResponseResult.success(service.createChannel(c));}@PutMapping("/channels/{id}")public ResponseResult<ChannelDTO>update(@PathVariable Long id,@Valid @RequestBody ChannelDTO c){return ResponseResult.success(service.updateChannel(id,c));}@PatchMapping("/channels/{id}/status")public ResponseResult<ChannelDTO>status(@PathVariable Long id,@RequestParam String status){return ResponseResult.success(service.channelStatus(id,status));}@DeleteMapping("/channels/{id}")public ResponseResult<Void>delete(@PathVariable Long id){service.deleteChannel(id);return ResponseResult.success(null);}
 public record LoginRequest(@NotBlank @Size(max=64)String name,@NotBlank @Size(min=6,max=72)String password){}public record RejectRequest(@NotBlank @Size(max=500)String reason){}
}
