package com.aaliyun.leadnews.schedule.service;
import com.aaliyun.leadnews.feign.article.ArticleInternalClient;import com.aaliyun.leadnews.model.foundation.*;import com.aaliyun.leadnews.schedule.config.ScheduleProperties;import com.aaliyun.leadnews.schedule.domain.ScheduleTask;import com.aaliyun.leadnews.schedule.mapper.ScheduleTaskMapper;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper;import jakarta.annotation.PostConstruct;import org.slf4j.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.data.redis.core.StringRedisTemplate;import org.springframework.scheduling.annotation.Scheduled;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.time.ZoneOffset;import java.util.*;
@Service public class PublishTaskService{public static final String FUTURE_KEY="schedule:publish:future";private static final Logger log=LoggerFactory.getLogger(PublishTaskService.class);private final ScheduleTaskMapper tasks;private final StringRedisTemplate redis;private final ArticleInternalClient article;private final ScheduleProperties props;public PublishTaskService(ScheduleTaskMapper t,StringRedisTemplate r,ArticleInternalClient a,ScheduleProperties p){tasks=t;redis=r;article=a;props=p;}
 @Transactional public Long create(ScheduleTaskCommand c){ScheduleTask old=tasks.selectOne(new LambdaQueryWrapper<ScheduleTask>().eq(ScheduleTask::getTaskType,"ARTICLE_PUBLISH").eq(ScheduleTask::getBusinessId,c.articleId()).eq(ScheduleTask::getDeleted,false));if(old!=null){enqueue(old);return old.getId();}ScheduleTask t=new ScheduleTask();t.setTaskType("ARTICLE_PUBLISH");t.setBusinessId(c.articleId());t.setExecuteTime(c.executeTime());t.setStatus("WAITING");t.setRetryCount(0);try{tasks.insert(t);}catch(DuplicateKeyException e){return create(c);}enqueue(t);return t.getId();}
 @PostConstruct public void restore(){List<ScheduleTask> waiting=tasks.selectList(new LambdaQueryWrapper<ScheduleTask>().in(ScheduleTask::getStatus,List.of("WAITING","READY","FAILED")).eq(ScheduleTask::getDeleted,false));waiting.forEach(this::enqueue);}
 @Scheduled(fixedDelayString="${leadnews.schedule.scan-interval:PT1S}")public void scan(){long max=System.currentTimeMillis()+props.preloadWindow().toMillis();Set<String> ids=redis.opsForZSet().rangeByScore(FUTURE_KEY,0,max);if(ids==null)return;for(String id:ids){redis.opsForZSet().remove(FUTURE_KEY,id);execute(Long.valueOf(id));}}
 public void execute(Long id){ScheduleTask t=tasks.selectById(id);if(t==null||Set.of("SUCCESS","CANCELLED").contains(t.getStatus()))return;if(t.getExecuteTime().isAfter(LocalDateTime.now())){enqueue(t);return;}int claim=tasks.update(null,new LambdaUpdateWrapper<ScheduleTask>().eq(ScheduleTask::getId,id).in(ScheduleTask::getStatus,List.of("WAITING","READY","FAILED")).set(ScheduleTask::getStatus,"RUNNING").set(ScheduleTask::getStartedTime,LocalDateTime.now()));if(claim!=1)return;try{article.publish(t.getBusinessId());tasks.update(null,new LambdaUpdateWrapper<ScheduleTask>().eq(ScheduleTask::getId,id).eq(ScheduleTask::getStatus,"RUNNING").set(ScheduleTask::getStatus,"SUCCESS").set(ScheduleTask::getLastError,null));}catch(Exception e){ScheduleTask current=tasks.selectById(id);int retry=current.getRetryCount()+1;String status=retry>=props.maxRetries()?"FAILED":"WAITING";LocalDateTime next=LocalDateTime.now().plus(props.retryDelay());tasks.update(null,new LambdaUpdateWrapper<ScheduleTask>().eq(ScheduleTask::getId,id).eq(ScheduleTask::getStatus,"RUNNING").set(ScheduleTask::getStatus,status).set(ScheduleTask::getRetryCount,retry).set(ScheduleTask::getExecuteTime,next).set(ScheduleTask::getLastError,safe(e)));if("WAITING".equals(status)){current=tasks.selectById(id);enqueue(current);}log.warn("Scheduled article publish failed taskId={} retry={}",id,retry,e);}}
 private void enqueue(ScheduleTask t){long score=t.getExecuteTime().atZone(ZoneId.systemDefault()).toInstant().toEpochMilli();redis.opsForZSet().add(FUTURE_KEY,String.valueOf(t.getId()),score);}private String safe(Exception e){String m=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();return m.length()>500?m.substring(0,500):m;}
}
