package com.aaliyun.leadnews.search.service;
import co.elastic.clients.elasticsearch.*;import co.elastic.clients.elasticsearch._types.ElasticsearchException;import co.elastic.clients.elasticsearch._types.VersionType;import co.elastic.clients.elasticsearch.core.*;import co.elastic.clients.elasticsearch.core.bulk.BulkOperation;import com.aaliyun.leadnews.model.search.ArticleSearchDocument;import com.aaliyun.leadnews.search.config.SearchIndexInitializer;import org.springframework.stereotype.Service;import java.io.IOException;import java.util.*;
@Service public class ArticleIndexService {
 private final ElasticsearchClient client;public ArticleIndexService(ElasticsearchClient c){client=c;}
 public void upsert(ArticleSearchDocument d)throws IOException{writeArticle(d);writeSuggestion(d);}
 public void tombstone(Long id,long version)throws IOException{Map<String,Object>t=Map.of("articleId",id,"articleVersion",version,"deleted",true);write(SearchIndexInitializer.ARTICLE_ALIAS,id,version,t);write(SearchIndexInitializer.SUGGEST_ALIAS,id,version,t);}
 private void writeArticle(ArticleSearchDocument d)throws IOException{write(SearchIndexInitializer.ARTICLE_ALIAS,d.articleId(),d.articleVersion(),d);}
 private void writeSuggestion(ArticleSearchDocument d)throws IOException{Map<String,Object>s=new HashMap<>();s.put("articleId",d.articleId());s.put("articleVersion",d.articleVersion());s.put("deleted",false);s.put("title",d.title());s.put("suggestion",String.join(" ",combine(d.title(),d.labels())));s.put("labels",d.labels());write(SearchIndexInitializer.SUGGEST_ALIAS,d.articleId(),d.articleVersion(),s);}
 private void write(String index,Long id,long version,Object document)throws IOException{try{client.index(i->i.index(index).id(id.toString()).version(version).versionType(VersionType.External).document(document));}catch(ElasticsearchException e){if(e.status()==409)return;throw e;}}
 public void bulk(List<ArticleSearchDocument>docs)throws IOException{if(docs.isEmpty())return;List<BulkOperation>ops=new ArrayList<>();for(ArticleSearchDocument d:docs){ops.add(BulkOperation.of(o->o.index(i->i.index(SearchIndexInitializer.ARTICLE_ALIAS).id(d.articleId().toString()).version(d.articleVersion()).versionType(VersionType.External).document(d))));Map<String,Object>s=new HashMap<>();s.put("articleId",d.articleId());s.put("articleVersion",d.articleVersion());s.put("deleted",false);s.put("title",d.title());s.put("suggestion",String.join(" ",combine(d.title(),d.labels())));s.put("labels",d.labels());ops.add(BulkOperation.of(o->o.index(i->i.index(SearchIndexInitializer.SUGGEST_ALIAS).id(d.articleId().toString()).version(d.articleVersion()).versionType(VersionType.External).document(s))));}BulkResponse r=client.bulk(b->b.operations(ops));if(r.items().stream().anyMatch(x->x.error()!=null&&x.status()!=409))throw new IOException("Elasticsearch bulk contained non-version-conflict failures");}
 public void clearForRebuild()throws IOException{client.deleteByQuery(q->q.index(SearchIndexInitializer.ARTICLE_ALIAS).query(x->x.matchAll(m->m)));client.deleteByQuery(q->q.index(SearchIndexInitializer.SUGGEST_ALIAS).query(x->x.matchAll(m->m)));}
 private List<String>combine(String title,List<String>labels){List<String>all=new ArrayList<>();all.add(title);if(labels!=null)all.addAll(labels);return all;}
}
