package com.aaliyun.leadnews.wemedia.service;
import com.aaliyun.leadnews.common.api.CommonErrorCode;import com.aaliyun.leadnews.common.context.UserContext;import com.aaliyun.leadnews.common.exception.BusinessException;import com.aaliyun.leadnews.wemedia.config.WemediaMinioProperties;import com.aaliyun.leadnews.wemedia.domain.*;import com.aaliyun.leadnews.wemedia.mapper.*;import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;import io.minio.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.multipart.MultipartFile;import java.io.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;import javax.imageio.ImageIO;
@Service public class MaterialStorageService{private final MinioClient minio;private final WemediaMinioProperties p;private final WmMaterialMapper materials;private final WmNewsMaterialMapper refs;public MaterialStorageService(MinioClient m,WemediaMinioProperties p,WmMaterialMapper ms,WmNewsMaterialMapper r){minio=m;this.p=p;materials=ms;refs=r;}
 @Transactional public WmMaterial upload(MultipartFile file){Long user=owner();if(file==null||file.isEmpty()||file.getSize()>p.maxImageSize())throw new BusinessException(40000,"Image is empty or exceeds size limit");try{byte[] bytes=file.getBytes();ImageType type=detect(bytes);validateDimensions(bytes,p.maxImagePixels());String key="material/"+user+"/"+LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy/MM/dd"))+"/"+UUID.randomUUID()+"."+type.ext;ensureBucket();minio.putObject(PutObjectArgs.builder().bucket(p.bucket()).object(key).stream(new ByteArrayInputStream(bytes),bytes.length,-1).contentType(type.mime).build());WmMaterial m=new WmMaterial();m.setUserId(user);m.setObjectKey(key);m.setUrl(p.publicEndpoint()+"/"+p.bucket()+"/"+key);m.setMaterialType("IMAGE");m.setCollected(false);materials.insert(m);return m;}catch(BusinessException e){throw e;}catch(Exception e){throw new BusinessException(50300,"Material upload failed");}}
 @Transactional public void delete(Long id){WmMaterial m=materials.selectById(id);if(m==null||!owner().equals(m.getUserId()))throw new BusinessException(40400,"Material not found");Long count=refs.selectCount(new LambdaQueryWrapper<WmNewsMaterial>().eq(WmNewsMaterial::getMaterialId,id));if(count>0)throw new BusinessException(40900,"Material is referenced by news");try{minio.removeObject(RemoveObjectArgs.builder().bucket(p.bucket()).object(m.getObjectKey()).build());materials.deleteById(id);}catch(Exception e){throw new BusinessException(50300,"Material deletion failed");}}
 private Long owner(){if(!UserContext.isType("WEMEDIA")||UserContext.getUserId()==null)throw new BusinessException(CommonErrorCode.AUTH_FORBIDDEN);return UserContext.getUserId();}private void ensureBucket()throws Exception{if(!minio.bucketExists(BucketExistsArgs.builder().bucket(p.bucket()).build()))minio.makeBucket(MakeBucketArgs.builder().bucket(p.bucket()).build());}
 static ImageType detect(byte[] b){if(b.length>=3&&(b[0]&255)==255&&(b[1]&255)==216&&(b[2]&255)==255)return new ImageType("jpg","image/jpeg");if(b.length>=8&&(b[0]&255)==137&&b[1]==80&&b[2]==78&&b[3]==71)return new ImageType("png","image/png");if(b.length>=6&&b[0]=='G'&&b[1]=='I'&&b[2]=='F')return new ImageType("gif","image/gif");if(b.length>=12&&b[0]=='R'&&b[1]=='I'&&b[2]=='F'&&b[8]=='W'&&b[9]=='E'&&b[10]=='B'&&b[11]=='P')return new ImageType("webp","image/webp");throw new BusinessException(40000,"Only JPEG, PNG, GIF or WebP image bytes are accepted");}record ImageType(String ext,String mime){}
 static void validateDimensions(byte[] bytes,long maxPixels){try(var input=ImageIO.createImageInputStream(new ByteArrayInputStream(bytes))){var readers=ImageIO.getImageReaders(input);if(!readers.hasNext())throw new BusinessException(40000,"Image dimensions cannot be validated by this server");var reader=readers.next();try{reader.setInput(input,true,true);long pixels=Math.multiplyExact((long)reader.getWidth(0),reader.getHeight(0));if(pixels>maxPixels)throw new BusinessException(40000,"Image resolution exceeds configured pixel limit");}finally{reader.dispose();}}catch(BusinessException e){throw e;}catch(Exception e){throw new BusinessException(40000,"Image dimensions are invalid");}}
}
